### ISSUE TITLE
Write up TCC data sharing prototyping week report

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/local-intelligence-hub#1]

**Comment by zarino** [comment]
A draft of the report has been completed, and shared with TCC.

**Comment by zarino** [comment]
TCC have shared some additional tester feedback with us (collected via Google Forms) so it’d be good to include that in the write-up.

They are also going to get back to us with any comments / amendments, after they‘ve had a chance to read it through.

**Comment by zarino** [comment]
This has now been finalised and published: https://research.mysociety.org/publications/prototyping-data
