### ISSUE TITLE
Import Net Zero Scrutiny Group membership data

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#109]
The NZSG doesn’t publish its own list of members, but [DeSmog lists what it thinks are the key members](https://www.desmog.com/net-zero-scrutiny-group/).

Spreadsheet version: https://docs.google.com/spreadsheets/d/1NErRYSYKdIk2nwugRNwZNKDIxdpgXWaQF5LGVXfvLtA/edit

~~Like with #108, Green Alliance have a copy of this as part of their MP target list – could get it from there, or from the website, if it’s not much harder.~~

**Comment by alexander-griffen** [comment]
Closed with #138
