### ISSUE TITLE
Averages are only for areas with data, and not including areas with no data

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#110]
Need to calculate the total and the divide by the number of constituencies.

**Comment by zarino** [comment]
Also, related to this: For most datasets, on the individual area page, I think we want to show a "0" if the constituency has no data, rather than often showing nothing at all (eg: Save The Children Shops).

**Comment by struan** [comment]
Probably need to add a post import action that gets this list of areas without a value and adds a zero entry. I guess if we add it to the base importer and run it by default on all numeric imports, with a flag to turn it off, that should cover most of it.

Can always add a management command to fix existing ones.

**Comment by zarino** [comment]
FYI @struan – @alexander-griffen made a start on something here https://github.com/mysociety/local-intelligence-hub/pull/211
