### ISSUE TITLE
Explore page: Improve shader scaling and presentation

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#119]
Shaders currently:

- Use a scale based on the min and max values from the entire dataset (min and max values generated at dataset import time, not map query time).
- Use only the opacity of polygons to represent the percentage.

Instead, shaders should:

- Use a scale based on the minimum and maximum values from _the constituencies matching the current filters_, so the visible constituency on the map with the lowest value in the chosen shader dataset will always have a "shade" of 0%, and the visible constituency on the map with the highest value will always have a "shade" of 100% – even if those constituencies would actually be somewhere in the middle of the pack if you looked at all 650 constituencies as a whole. In other words, the scale shouldn’t be based on all 650 constituencies, it should only be based on the constituencies matching the current filter(s).
- Use a colour scale, [like Viridis or Magma](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html) and keep fill and stroke opacities at 100%.

Not for the MVP, but a nice-to-have would be:

- Display a key/legend somewhere, to explain the scale, showing the entire scale as a gradient, with the minimum and maximum values at either end.

**Comment by struan** [comment]
You can't make it 0% as then you can't distinguish constituencies that have been filtered out or have no data.
