### ISSUE TITLE
Add a contains comparator for things like select committees

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#135]
At the moment the comparator for select committees and APPGs used an exact match which means you need to know the specific name of the select committee to generate a match, which is not ideal. We should probably add a comparator that does a `contains` filter so people can, e.g put in 'environment' rather than having to know it is 'Environment, Food and Rural Affairs Committee'

**Comment by alexander-griffen** [comment]
It might be useful for us to make one for booleans as well (or at least, a way of displaying them in the filter to avoid having to type 'True' for the current 'is')
