### ISSUE TITLE
Christian Aid campaign organisers

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#163]
Only a few postcodes here, saved in the shared Drive.

**Comment by alexander-griffen** [comment]
I've manually inputted the constituencies into this (as it's faster than writing to MapIt code, just about). What entry should be used for Belfast, given that there are multiple constituencies in Belfast, or should it be skipped?

**Comment by zarino** [comment]
@alexander-griffen For now, I’d just skip the Belfast ones. We might be getting updated data from Christian Aid as part of the six-monthly update anyway.
