### ISSUE TITLE
Party vote split at most recent election in constituency (to help identify “battleground” seats)

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#169]
We already have MP majority data, which lets us tag constituencies with a majority of less than 5000 as "marginals".

<img width="535" alt="Screenshot 2023-02-14 at 18 09 24" src="https://user-images.githubusercontent.com/739624/218821587-c619c5f0-2e13-4576-b3dd-04bda4bab02f.png">

But campaigners will often want to be more specific, and focus down to just marginals where the MP and the runner up were from a given two parties (eg: "Labour/Tory marginals" or "SNP/Labour marginals").

There are a couple of ways we could do this:

1. A **"battleground seat" dataset** for each constituency, which is hand-compiled and a bit of a black box (as it happens, Flossie has already compiled this) but would allow you to, in pseudo-SQL:

   ```
   WHERE `Battleground seat` == "Labour/Conservative marginal"
   ```

   The thing I don’t like about this is that it‘s a dataset _based_ on raw numbers, some of which we _do_ actually hold in the database, but it isn’t actually calculated _from_ those numbers. Feels yucky. And also relies on someone manually updating the list whenever by-elections are held.

2. A **"top two parties" dataset** for each constituency – which breaks out the "majority" aspect of the battleground, and leaves just the party pairing, allowing you to select, for example:

   ```
   WHERE `MP majority` < 5000 AND `Top two parties` == "Labour/Conservative"
   ```

3. A **"second most popular party" dataset** for each constituency – meaning you’d be able to do, eg:

   ```
   WHERE `MP majority` < 5000 AND `MP party` == "Labour" AND `Second most popular party` == "Conservative"
   ```

   …but, [unless we _also_ implemented #168](https://github.com/mysociety/local-intelligence-hub/issues/168), you wouldn’t be able to do this:

   ```
   WHERE `MP majority` < 5000 AND `MP party` IN ("Labour", "Conservative") AND `Second most popular party` IN ("Labour", "Conservative")
   ```

@alexander-griffen @struan any thoughts on the merits / challenges of these approaches?

Related: It feels like importing (and displaying on the area page) the _full_ party vote split for the constituency, at its last election, would also be a useful thing.

Note: Ideally we’d display data from the most recent election in the constituency, which might be a by-election, rather than the 2019 general election.

### Data sources

2019 general election party vote split data is available from UK Parliament here: https://researchbriefings.files.parliament.uk/documents/CBP-8749/HoC-GE2019-results-by-constituency-csv.csv

And UK Parliament also has a spreadsheet of by-elections _since_ the 2019 general election here: https://researchbriefings.files.parliament.uk/documents/CBP-9225/Data-file.xlsx

**Comment by struan** [comment]
Having had a think about this I think that we should import the most recent election results as a JSON thing and display them, and as with all the JSON things, this should not be filterable.

We can then have a separate import for the 2nd place part and use the multiple select stuff from #168 to enable people to search for that in combination with the current MP party and election majority to find the marginals they are interested in.

It doesn't, I guess, handle three way marginals but I feel that there are so few of them we can ignore them. 

This is useful data - https://commonslibrary.parliament.uk/general-election-2019-marginality/ which says there were 17 three way marginals at the last election.

I do wonder if a %age margin might be helpful for this as that's what that report talks about. Shouldn't be too hard to do, and is useful for by-elections where the turnout tends to be lower.

**Comment by struan** [comment]
On a second note, it's weird that the by-election data has %age turnout and %age margin and the GE results do not.

**Comment by zarino** [comment]
Thanks @struan !
