### ISSUE TITLE
Launch live version

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#193]
- [x] Set up live vhost, at TCC-supplied domain – https://github.com/mysociety/sysadmin/issues/1770
- [x] Import data into live database
- [x] Set up first batch of users on live site
- [ ] Add a big banner to staging site, telling people to use the live site instead
- [x] Clear login sessions from staging site (logging everyone out)
- [x] Disable or change passwords of `tcc-staging` and `demo` accounts on staging site

**Comment by JenMysoc** [comment]
Is this not all done now since launch was around 2 weeks ago?

**Comment by zarino** [comment]
@JenMysoc I still want to add some sort of custom styling to the staging site, so that it’s _really clear_ that it’s not the live site – just in case someone accidentally follows the wrong link. Hoping to get round to this this sprint.

**Comment by struan** [comment]
I've set all the non mysociety account to inactive which will stop them using the site. Don't need to remove the sessions as setting the account to inactive is enough.
