### ISSUE TITLE
Flood risk data

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#195]
There are a number of flood risk datasets on https://www.data.gov.uk/search?q=flood+risk, but they all seem to be Shapefiles 🤔

**Comment by JuliaNgoga** [comment]
Gov [website](https://www.gov.uk/check-long-term-flood-risk) 
[Environment Agency ](https://www.data.gov.uk/dataset/42c31542-228d-439b-8dbe-e72135dae71c/flood-risk-areas)- data link [here](https://www.data.gov.uk/dataset/bad20199-6d39-4aad-8564-26a46778fd94/risk-of-flooding-from-rivers-and-sea).
