### ISSUE TITLE
Development plan for TCC work

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/local-intelligence-hub#2]
To be sent to TCC along with the report so they can take to funders

**Comment by zarino** [comment]
This has been sent to TCC for discussion tomorrow.

**Comment by zarino** [comment]
TCC have requested a little more detail on:

- Features of MVP vs final Product (to help them explain what we’re planning to stakeholders)
- What input we’ll need from them, and when

Might also want to include an indicative timeline?

**Comment by JenMysoc** [comment]
Draft of current plan in G-Drive (post link?) needs some tweaking

**Comment by zarino** [comment]
[The Climate Coalition data sharing platform: Technical Specification](https://docs.google.com/document/d/1VgvSEcNBbmlo6BEJfWzERvz0x3dAFKQgm8kKN7iFpAc/edit)

[The Climate Coalition data sharing platform: Plan for Beta stage](https://docs.google.com/document/d/1QJ-Jdvg5CzPUtTmpl7lA8eSeYlQ1o8eu6BQK9Zsz5xQ/edit)

**Comment by JenMysoc** [comment]
TCC have seen and have said they're happy with this on our Monday call so we can consider this done as a first version. It's obviously a working document.
