### ISSUE TITLE
Local authority climate actions (emergency declaration, net zero target dates, plans)

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#204]
Three related questions, hopefully all can be answered by data from [the CAPE JSON API](https://cape.mysociety.org/api/councils/)

- Has the local authority covering this constituency declared a climate emergency?
   - Filter label: "Council declared climate emergency", data type: boolean
- Has the local authority covering this constituency published a climate action plan?
    - Filter label: "Council has climate action plan", data type: boolean
- Has the local authority covering this constituency declared a net zero target date, and if so, what for (council operations or whole area) and what year?
    - Filter label: "Council net zero target date", subtypes: "Council operations only" / "Whole area", data type: year

Will need to think about the best way to display this data on the Area page. Perhaps all together, in the same card?

**Comment by juliacush** [comment]
Net zero target date info displaying strangely 

![Image](https://github.com/mysociety/local-intelligence-hub/assets/135219396/6336f422-298f-4eb5-96a6-e689979859d5)

**Comment by zarino** [comment]
@juliacush the "strange" display is because you really _shouldn’t_ be able to add JSON datasets like that as a column in first place: https://github.com/mysociety/local-intelligence-hub/issues/496

**Comment by struan** [comment]
done in #507
