### ISSUE TITLE
Reconsider Area page layout, to handle more datasets in future

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#210]
The current Area page layout is already groaning under too many datasets, requiring users to do lots of scrolling around, and making it harder to pick out the dataset you’re interested in.

The current layout is also _heavily_ stage-managed, and with each new dataset we add to the site, we have to rejig the boxes on the Area page to make room.

This is okay (ish) for an initial launch. But we should spend some time thinking about the best way to solve this in the longer term.

**Comment by alexander-griffen** [comment]
In terms of the structure of the templates, the partials are mostly decided by the (human-understandable) context of the data (e.g. is it Place data, or about Opinion, etc?). It might be easier to separate them out based on how the data is displayed (Just a stat, a stat with an average, or table or graph, etc etc). This would also reduce duplicate code across the templates.

If this would make the redesigning of the area page layout easier, I'd be happy to pick it up
