### ISSUE TITLE
organisation set up: 3 days (very rough guess based on zero investigation)

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#215]

**Comment by zarino** [comment]
The account request process currently asks people to provide an "Organisation" string, free text. That’s good enough for now, given we don’t _actually_ need to do anything programmatic with organisations. And if/when we _do_ want to set up an organisation model (to limit access to datasets, for example) we could maybe infer the starter set of orgs from these free text strings.

Closing this ticket in the meantime.
