### ISSUE TITLE
Data Protection Impact Assessment and documentation

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#219]
See https://github.com/mysociety/sysadmin/issues/1766.

- Data Protection Impact Assessment
- Datasets added to mySociety’s Information Asset Register

Related: #69

**Comment by zarino** [comment]
I have [started a DPIA here](https://docs.google.com/document/d/17bYpkj03DCWLENHJRuvQ7jvEm1PfHIEI_q3xFIwj-pk/edit), and will get @sagepe’s input on it next week.

**Comment by sagepe** [comment]
As noted on https://github.com/mysociety/sysadmin/issues/1446, our Information Asset Register is currently formed of notes and links on the [GDPR](https://wiki.mysociety.org/wiki/General_Data_Protection_Regulation_(GDPR)#Personal_data_processed_by_our_applications) and [Data Protection](https://wiki.mysociety.org/wiki/Data_Protection#Detailed_data_protection_policies_and_procedures) wiki pages.
