### ISSUE TITLE
Annotate datasets with information for future combining

### ISSUE THREAD

**Issue by ajparsons** [mysociety/local-intelligence-hub#254]
To prepare for automatic translations, for each dataset, store if the data is best expressed as:

1. A raw unit (people, buildings) or a percentage.
2. If it is more correct to see that unit or percentage as being evenly distributed over ‘people in an area’ or ‘the physical area’.

[This ticket is part of the [new constituency data](https://docs.google.com/document/d/144CO0QeVzVbNLFtCafB2rNl54AqHJZtfI3oAL0oFMpk/edit#) plan]

**Comment by alexander-griffen** [comment]
There's a number of datasets which are provided as point data in various forms. An extra column can be made to mark it as such, so that scripts which use it can be altered to accomodate different `Area` types in the future.
