### ISSUE TITLE
Automatically create local authority level info from constituency level info.

### ISSUE THREAD

**Issue by ajparsons** [mysociety/local-intelligence-hub#255]
Incorporate an automatic transformation process from “old” constituency data to local authorities into LiH. This will be useful in itself, but also create the framework for creating derived datasets that can be widely applied later on to new constituencies.

More details in the doc.

[This ticket is part of the [new constituency data](https://docs.google.com/document/d/144CO0QeVzVbNLFtCafB2rNl54AqHJZtfI3oAL0oFMpk/edit#) plan]

**Comment by struan** [comment]
FWIW, I've done this with lots of the point data (members, locations etc)

**Comment by struan** [comment]
This is partially done but isn't really automated and only in place really for postcode based datasets.
