### ISSUE TITLE
Support multiple geographies

### ISSUE THREAD

**Issue by ajparsons** [mysociety/local-intelligence-hub#256]
Add support for multiple geographies to LiH, initially to set up an extra map for local authorities, but this is also creating a framework to plug the new constituencies into. 

More details in the doc.

[This ticket is part of the [new constituency data](https://docs.google.com/document/d/144CO0QeVzVbNLFtCafB2rNl54AqHJZtfI3oAL0oFMpk/edit#) plan]

- [x] import new constituencies
- [x] enable swapping area types on explore page
- [x] display new boundaries on explore page
- [x] #334
- [x] #335
- [x] #336
- [x] #337
- [x] #360

**Comment by alexander-griffen** [comment]
## Update
Done so far:
- Adding the `AreaType` model is ready to review [(PR)](https://github.com/mysociety/local-intelligence-hub/pull/310)
Next steps:
- Reviewing [prep work document](https://docs.google.com/document/d/1975tU3XU7LGTFLHeF4vnrylhaz3bDffE9RNplF4dmOQ), and comments. Updating to reflect these changes
- Implementing changes to `DataSet` and `DataType` models to accomodate multiple `AreaType`s

**Comment by zarino** [comment]
Done!! 🎉
