### ISSUE TITLE
Create old/new constituency lookups and update existing datasets

### ISSUE THREAD

**Issue by ajparsons** [mysociety/local-intelligence-hub#257]
On release of final constituency boundaries in July.

Create new lookups:

- Update our small area datasets (IMD, etc) to new constituency boundaries (either using new, or Friends of the Earth lookups)
- Create a new area/population overlap dataset between old and new constituencies and update.

Then, building on the previous work:

- Add new constituencies as a new geography. 
- Add old-to-new constituencies process and auto transform all current data.

More details in the doc.

[This ticket is part of the [new constituency data](https://docs.google.com/document/d/144CO0QeVzVbNLFtCafB2rNl54AqHJZtfI3oAL0oFMpk/edit#) plan]

**Comment by ajparsons** [comment]
I've done the underlying data work to enable data to be transformed. 

--

The shapefile for new constituencies - along with a set of common ids is at https://pages.mysociety.org/2025-constituencies/datasets/parliament_con_2025/latest

There is also (for GB but not NI) - a postcode lookup for converting postcode data: https://pages.mysociety.org/2025-constituencies/datasets/uk_parliament_2025_postcode_lookup/latest

--

I've reduced the geographic conversion tool into a single file that pulls the lookup tables from the web:

https://github.com/mysociety/climate_mrp_polling/blob/main/src/climate_mrp_polling/convert_polling.py

In principle, you can drop that file into the local intelligence hub and use it to convert data between PARL10 and PARL25. 

--

New 2025 constituency level data is available for:

* IMD -  https://pages.mysociety.org/composite_uk_imd/downloads/uk-index-parl25-imd-csv/latest
* RUC -  https://pages.mysociety.org/uk_ruc/downloads/uk-ruc-pcon-2025-ruc-csv/latest

**Comment by zarino** [comment]
Done done! As part of #305.
