### ISSUE TITLE
Local Intelligence Hub public launch

### ISSUE THREAD

**Issue by sequencefree** [mysociety/local-intelligence-hub#265]
**Next steps**

- [ ] @zarino to introduce @sequencefree to Jake @ TCC.
- [ ] @sequencefree to arrange chat with Jake and @MyfanwyNixon to get the ball rolling on a comms plan.

**Background**

Scraped from Slack (20230516):

Zarino Zappia
  [6 hours ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684233448284829)
[@Siôn](https://mysociety.slack.com/team/U02B4MZFJCB)
 
[@Myf](https://mysociety.slack.com/team/U2CG4KSEN)
 I’m doing some very finger-in-the-air scheduling and wondering when we should plan for a public “launch” for Local Intelligence Hub… rushing it out before the school holidays start on 1st August feels challenging, but then I don’t know how much school holidays should worry us or not. Any thoughts?
:+1::skin-tone-2:
1

Jen Bramley
  [6 hours ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684233953553319?thread_ts=1684233448.284829&cid=CHL40EKB9)
School holiday start on July 21st

Jen Bramley
  [6 hours ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684233966423869?thread_ts=1684233448.284829&cid=CHL40EKB9)
and will end on around Sept 4th

Siôn Elis Williams
:hammer:  [6 hours ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684233970972499?thread_ts=1684233448.284829&cid=CHL40EKB9)
Generally a good move to get stuff like this out when things are calmer on the political front and [looks like that fits with Parliamentary recess](https://www.parliament.uk/about/faqs/house-of-commons-faqs/business-faq-page/recess-dates/).
Also gives people time to play with it ahead of political party conference season, where I can see it might help politicos to target politicians and potentially with engaging them.
I guess our other audience is grassroots activists, and it can take time for stuff to trickle down to them via NGO staff so generally sooner the better on that front I reckon.
Only other thing that occurs to me is potential activists and whether we might want to try and line up some media coverage, perhaps by working w/The Climate Coalition.
One of the benefits of this kind of site is its storytelling potential, so maybe we could work with someone to extract a story that we think is newsworthy and/or even relates to our other work e.g NW?

Jen Bramley
  [6 hours ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684234026269959?thread_ts=1684233448.284829&cid=CHL40EKB9)
Is there any more rumbling about general elections that you've heard?

Siôn Elis Williams
:hammer:  [6 hours ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684234250305049?thread_ts=1684233448.284829&cid=CHL40EKB9)
Not really tracking GE but assuming about 16 months away.
Have we demonstrated this to any data journos?
Could be interesting to chuck it at someone like https://www.owenboswarva.com/ and work with them on a story.

Siôn Elis Williams
:hammer:  [6 hours ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684234320845639?thread_ts=1684233448.284829&cid=CHL40EKB9)
Not to early to frame around the election though I reckon. (edited) 

Zarino Zappia
  [6 hours ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684234408113659?thread_ts=1684233448.284829&cid=CHL40EKB9)
I am starting to think 
[@Siôn](https://mysociety.slack.com/team/U02B4MZFJCB)
 I should link you up with Jake at TCC sooner rather than later – he’s getting increasingly busy in the run-up to Great Big Green Week (10th–18th June) but if we leave it until after that to start planning, I’m worried there might not be much time
:yesyes:
1

Jen Bramley
  [6 hours ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684234474528369?thread_ts=1684233448.284829&cid=CHL40EKB9)
Also, for Emily's benefit (as this is what I would have wanted) and idea of what work would be included in the launch and roughly how long it might take would be ace
:+1::skin-tone-2::+1:
2

Myf Nixon
  [6 hours ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684234920404909?thread_ts=1684233448.284829&cid=CHL40EKB9)
Haven't read the whole thread yet, but I'm away in early August if that makes a difference

Myf Nixon
  [6 hours ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684234941023299?thread_ts=1684233448.284829&cid=CHL40EKB9)
Until the 17th

Myf Nixon
  [6 hours ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684234998988119?thread_ts=1684233448.284829&cid=CHL40EKB9)
Have now read the whole thread

Siôn Elis Williams
:hammer:  [1 hour ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684249873553799?thread_ts=1684233448.284829&cid=CHL40EKB9)
Is there a ticket for public launch Zarino?
Happy to create one here if not: https://github.com/mysociety/local-intelligence-hub/issues
New

Zarino Zappia
  [1 hour ago](https://mysociety.slack.com/archives/CHL40EKB9/p1684249946840619?thread_ts=1684233448.284829&cid=CHL40EKB9)
yeah, there isn’t a ticket for a launch yet – go ahead and create one

**Comment by JenMysoc** [comment]
We need a list of exactly what we expect to happen when, both on launch day and on the run up to launch.

@MyfanwyNixon is this something you would be able to sketch out?

**Comment by MyfanwyNixon** [comment]
Yes, once I have been fully briefed!

**Comment by emilyk383** [comment]
@sequencefree ok if I close this issue? I think things have moved on a fair bit since this conv including now sitting with TCC (for timing and resourcing), me, and Myf for amplification on the comms front (we think) as and when it happens. I'd find it helpful to start with a clean ticket. And absolutely expect to consult / involve you in the launch strategy as it develops.
