### ISSUE TITLE
Increase email confirmation link validity period

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#275]
We’ve had feedback from some users that their email confirmation links had expired by the time they got round to responding to the email (which could have been _weeks_ later).

My instinct is that these links should basically never expire.

I know we [increased the `PASSWORD_RESET_TIMEOUT` from 3 days to 8 days in the CEUK marking app](https://github.com/mysociety/ceuk-marking/commit/360e54797c7c30e9ebb6c0c3b861bdc48789070e). Maybe we should do something similar here?

Although, does [`PASSWORD_RESET_TIMEOUT`](https://docs.djangoproject.com/en/4.2/ref/settings/#password-reset-timeout) even apply to the email confirmation links? Or is it _specifically_ for password resets? Needs some investigation.

**Comment by struan** [comment]
I'm not sure this can happen. There's nothing in the code that records when the token was created and nothing that renders a token invalid, apart from clicking on the link at which point the token is deleted. Possibly they clicked the link already, or some awful automation spam checking thing clicked the link on their behalf?

**Comment by zarino** [comment]
Hmmm. I’m going to close this ticket for now. We can re-open if the problem comes up again. (If the problem is indeed caused by antivirus / security systems pre-loading the token URL, I guess the solution would be to require a POST form submission to activate the user’s account and delete the token, rather than doing it on GET. Or to keep old tokens around for a while after they’re first used.)
