### ISSUE TITLE
Only allow logged-in users to see “members only” datasets on area, explore, and data source pages

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#280]
- [x] Enable public access to all pages of the site, add privacy field to dataset model
   - https://github.com/mysociety/local-intelligence-hub/pull/392

Below moved to #399
- [ ] Update all datasets to set privacy field – either public or private
- [ ] Will require us to mark datasets as public or private – [TCC have started a spreadsheet to collect this information](https://docs.google.com/spreadsheets/d/10nCxPl6-HPSel6gLQmhLWOfAWr0rImC6gXX2_lYzPjE/edit#gid=0) from partners / partner agreements [update 4/12/23]

**Comment by emilyk383** [comment]
Will require us to mark datasets as public or private – [TCC have started a spreadsheet to collect this information](https://docs.google.com/spreadsheets/d/10nCxPl6-HPSel6gLQmhLWOfAWr0rImC6gXX2_lYzPjE/edit#gid=0) from partners / partner agreements.
