### ISSUE TITLE
Sysadmin / capacity planning for a “public” launch

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#283]
Theoretically, TCC member organisations have a reach of 22 million people. If we’re planning launch comms with these members, we might get a small, but still significant, fraction of these people trying to use the site.

(More likely, it’ll be TCC member organisations _themselves_, and local chapters of those organisations, making use of the newly “public” site – rather than the "general public".)

We should coordinate with @sagepe well in advance of a launch, to estimate and prepare for increased traffic.

**Comment by emilyk383** [comment]
Sam / Emily, 7/9/23, Sysadmin for launches 

SCORECARDS LAUNCH
Not too concerned about traffic - even with written media

Try and run the Scorecards/CAPE sites on two application servers
To do with the search tool 

ACTIONS

Prob don’t need to put on two sites for the launch on the basis of:

Assumption - low thousands over course of a day - max

- [ ] EK check this with CEUK 

- [ ] EK ask Alex - current traffic levels for Scorecards 

- [ ] Sam - look at potential actions to scale up - SOLR (expects would take 1.5 days of Sam’s time to actually do)

- [ ] EK clue in Zarino, potential conv between Sam & Struan re development 


LOCAL INTELLIGENCE HUB LAUNCH

Currently running on one server - not the SOLR prob - so easier to get onto two.

ACTIONS

- [ ] Sam talk to Alexander/Struan about Sam doing that; maybe check database instant sizes 

- [ ] EK talk to TCC about what they think will happen. (This planning assumes: gentle trickle of information out - ongoing process of promotion). EK talk to Myf about general promo

**Comment by emilyk383** [comment]
Scorecards resolved, LIH not entirely - conclude this sprint through conv and plan with Sam. CC Alex, Zarino, Struan and Alexander

**Comment by emilyk383** [comment]
LIH on two servers, max expected traffic of 30k in a week well within what the system as set up can handle.
