### ISSUE TITLE
Make localintelligencehub.com work (in addition to www.localintelligencehub.com)

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#295]
Feels a bit weird that typing "localintelligencehub.com" into your browser (without the "www.") takes you to an SSL error page:

<img width="1370" alt="Screenshot 2023-07-17 at 13 29 28" src="https://github.com/mysociety/local-intelligence-hub/assets/739624/431f6588-f5e7-4abb-80bb-3b5f6e6f6e11">

The error is `SSL_ERROR_BAD_CERT_DOMAIN`.

**Comment by zarino** [comment]
I have emailed Kitty at TCC about changing the DNS.

**Comment by zarino** [comment]
Spoke to Kitty about this, and then we both realised that we’d faced this issue before (which is probably why we used A Records in the first place) – because GoDaddy doesn’t let you put a CNAME on the domain root. I’ll discuss options with @sagepe.

**Comment by sagepe** [comment]
Have fixed for now by adding the original Load Balancers back as well as the new ones. 

As discussed in Slack, the options going forward are:

* Update DNS, and be prepared that this might happen again if we need to move the load-balancers around.
* Configure the domain to use our DNS servers instead, so we can manage this in future.

The current records should be:

```
A    93.93.128.76
A    93.93.130.150
AAAA 2a00:1098:80:3b::1b:1
AAAA 2a00:1098:82:dd::1e:1
```

**Comment by zarino** [comment]
@sagepe has fixed this for now. I’ve raised the suggestion with TCC that, next time this happens (because eventually it will) it’ll probably be simpler just to switch to mySoc’s nameservers.

**Comment by sagepe** [comment]
@zarino - sorry, I probably wasn't clear, but ideally they do need to update the current records to the ones listed [above.](https://github.com/mysociety/local-intelligence-hub/issues/295#issuecomment-1667554162)

**Comment by zarino** [comment]
Ah, thanks @sagepe. I’ve emailed TCC to make those changes to the A and AAAA records.

**Comment by sagepe** [comment]
Thanks @zarino - I've updated the load-balancer config again, removing the old hosts.
