### ISSUE TITLE
MOU for TCC work

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/local-intelligence-hub#3]
Once the report has been approved, draft an MOU for the next stage of the work and get approved by Louise and the board

**Comment by JenMysoc** [comment]
Drafted: https://docs.google.com/document/d/1fgjAFL0zJM6pkhx23-qJhqtbiFQJR5YNF820ti3iH44/edit approved by mySoc, waiting for approval from TCC

**Comment by zarino** [comment]
MOU has been signed by @crowbot (for mySociety) and Bronwen (for TCC) 👍
