### ISSUE TITLE
Decide: Public access with or without logins?

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#330]
Access to data on the site is currently limited to users with an account. Users must request an account, and only requests from TCC members are approved.

We’d like to expand access (to non-sensitive data) to users _beyond_ direct TCC members (for example, to wider membership/supporter base of TCC member orgs themselves, and their local chapters, as well as to elected representatives and their offices, to funders, etc).

There are two ways we could do this:

1. Modify the existing account request flow to always immediately create an account that can access the "public" data, with an additional manual approval step for users who say they’re from a TCC member org and want access to the members-only data.
2. Modify the Area, Explore, and JSON API views to allow access to "public" data _without an active login session at all_, meaning public users don’t even need to request an account to access public data. For access to members-only data, users would need to request an account, and log in.

I’d initially anticipated option 2, but there _are_ advantages to option 1 (limiting public data to logged-in users):

- Nobody gets access to data without agreeing to the [terms of use](https://www.localintelligencehub.com/terms/).
- If a user breaks the terms of use, we can revoke their access to the data (although this isn’t a silver bullet – they _could_ just sign up for another free account, as we see occasionally on sites like WDTK).
- We can continue to collect accurate user/usage numbers, server-side (rather than via Google Analytics which is largely useless when you don’t let it store cookies).

There are also downsides to option 1:

- Adds friction for users – requesting an account, verifying email address, remembering a password, etc.
- Means that links shared publicly (eg: on social media) will lead to a login/signup wall.

**Comment by zarino** [comment]
Hannah (TCC’s) instinct is to go with Option 2 – she thinks we should reduce friction wherever possible and if we require people to create accounts, that might just be enough friction that some people don’t use the site. The benefit of public access also meaning that pages are more shareable is another benefit.

**Comment by juliacush** [comment]
yes that makes sense - I think the sharing argument is very persuasive!

**Comment by ajparsons** [comment]
Are there features (now or planned) that work best logged in? Saved views etc - thinking about our long term issues contacting users

**Comment by zarino** [comment]
We’ve decided to go ahead with option 2 (account-less public access), but we’ll keep in mind that, if possible, we could encourage the creation of _public_ accounts in future, to give people features like favouriting, etc – and that would help us track usage server-side, as well as giving users persistent profiles/settings.
