### ISSUE TITLE
update explore page filtering to respect selected area type

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#335]
- [x] update JS to pass the current area type to the filter end point
- [x] update the filtering to select data for the relevant area type

**Comment by struan** [comment]
Although doh! the data_type has an area_type on it so maybe I don't need this...

**Comment by struan** [comment]
Having thought about this a bit more, and written some code I think I do need this as it's going to make things much easier.

**Comment by zarino** [comment]
This is being / has been addressed as part of https://github.com/mysociety/local-intelligence-hub/pull/344

**Comment by zarino** [comment]
@struan I think this can be closed now, as #344 has been merged into #350 / `multiple-geometry-staging`?
