### ISSUE TITLE
handle switching area type on explore page when filters/shaders already selected

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#336]
Ideally this should transparently switch to filtering using the new area type but will ideally need handling for filters that do not work with new area type - mostly to indicate to the user that the filter is not available so will not be applied.

**Comment by zarino** [comment]
This is being / has been addressed as part of https://github.com/mysociety/local-intelligence-hub/pull/344

**Comment by zarino** [comment]
@struan I think this can be closed now, as #344 has been merged into #350 / `multiple-geometry-staging`?
