### ISSUE TITLE
Import constituency fuel poverty data

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#34]
We’re importing this now as it’s a good example of a topical, social issue for constituencies.

@sequencefree has offered to help source good data.

**Comment by struan** [comment]
This seems to have the relevant data: https://www.gov.uk/government/statistics/sub-regional-fuel-poverty-data-2022

**Comment by zarino** [comment]
This was closed by 35c361db425dd168eb3d99f2ceceecda39bd51ed
