### ISSUE TITLE
Fix broken imports

### ISSUE THREAD

**Issue by alexander-griffen** [mysociety/local-intelligence-hub#352]
A mass import revealed the following errors:   

- `import_onward_polling_data: 'dict' object has no attribute 'extend'`
- `import_red_blue_wall_constituencies: 'data_type'`
- `import_foe_supporters: 'dict' object has no attribute 'extend'`

These should be resolved.

**Comment by zarino** [comment]
These errors have been fixed as part of #350 and will be resolved when that is merged into `main`.
