### ISSUE TITLE
Display links to FoE constituency narrative PDFs for new constituencies

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#362]
FoE are preparing "constituency narrative" PDFs for the upcoming constituencies, and aiming to have them ready for January 2024. It’d be good to display a link to these on the new constituency pages once they’re ready.

Not all constituencies will have a PDF. Mike from FoE is going to provide us with a spreadsheet of constituencies and the URLs of their PDFs.

**Comment by emilyk383** [comment]
From TCC call notes on 3/1/22, Mike Childs emailed before Xmas with the new environmental data reports - what's the next step? @zarino or @struan to review data and see how we can incorporate.

**Comment by struan** [comment]
Do we have the links somewhere?

**Comment by zarino** [comment]
@struan Mike said he’d share them with us in January. I’ll chase.

**Comment by zarino** [comment]
@struan CSV now in the shared drive.

Mike has requested that the dataset be for TCC members only, for now, as the environmental reports aren’t final yet.

**Comment by zarino** [comment]
Closed by https://github.com/mysociety/local-intelligence-hub/pull/388
