### ISSUE TITLE
Allow users to subscribe to email notifications about new datasets (with optional signup to TCC and mySociety newsletters too)

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#377]
@MyfanwyNixon suggested that we could allow users to sign up to be notified when new datasets are added to the Hub. And while they’re at it, they could also (optionally) sign up to TCC and/or mySociety’s email newsletters. Nice idea!

Question for @MyfanwyNixon – was the idea that the notifications would be sent via a separate Mailchimp list?

Assuming this ticket will make heavy use of Mailchimp, whoever comes to implement it may want to check out [how caps interfaces directly with the Mailchimp API](https://github.com/mysociety/caps/blob/74603adf02d52c1ea3ec9cf6af4046eea119c3f7/caps/views.py#L791-L829) for code we could reuse in LIH.

**Comment by struan** [comment]
relevant: https://mailchimp.com/developer/marketing/api/lists/

**Comment by zarino** [comment]
@struan In case it helps you design the form, I’m imagining something like:

<img width="1432" alt="Screenshot 2024-01-17 at 12 05 14" src="https://github.com/mysociety/local-intelligence-hub/assets/739624/d3f07b33-4fca-4da8-b400-d6d3c8e3fb15">

Where the markup (again, in case that’s useful – expect it’ll be a pain to set up something _exactly_ like this, using Django and `bootstrap-django` forms) for that was:

```html
<form>
    <h2 class="h4">Want notifications when we add new data?</h2>
    <fieldset>
        <legend>Let us know your email address and we’ll notify you about new data:</legend>
        <div class="mb-3">
            <label class="form-label" for="name">Name</label>
            <input type="text" id="name" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label" for="email">Email address</label>
            <input type="email" id="email" class="form-control">
        </div>
    </fieldset>
    <fieldset>
        <legend>You can also, optionally, join our newsletters for more inspiration on data, democracy, and climate action:</legend>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="check1">
            <label class="form-check-label" for="check1">
                mySociety
                <a href="https://www.mysociety.org/privacy/">(privacy policy)</a>
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="check2">
            <label class="form-check-label" for="check2">
                The Climate Coalition
                <a href="https://www.theclimatecoalition.org/privacy-policy">(privacy policy)</a>
            </label>
        </div>
    </fieldset>
    <button type="submit" class="btn btn-primary mt-4">Subscribe</button>
</form>
```

**Comment by struan** [comment]
So, my understanding for this is the plan is that when a user signs up for this there are three things that can happen:

1: everyone who submits is added to our mailchimp with the "LIH data updates" interest. They also get a "From LIH" tag, which is a member thing, not a list/audience thing.
2: if they check the mySociety mailing list option they are added to the "climate news" interest
3: if they check the TCC mailing list option we sign them up to the TCC newsletter.

@ajparsons @MyfanwyNixon

**Comment by MyfanwyNixon** [comment]
that sounds good to me!

**Comment by struan** [comment]
Just to be clear, I think this is all dependent on https://github.com/mysociety/climate-project/issues/132?
