### ISSUE TITLE
Fetch PPC photos and display them on area page

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#379]
DC sometimes has candidate photos so we could update the PPC importer to fetch these and add them to the site.

**Comment by zarino** [comment]
I am going to aks Democracy Club whether they’re able to / happy to share the URLs for these images with us (given they’re not in the PPC data they’ve previously shared, and they also don’t appear to be in the API).

**Comment by struan** [comment]
This is no longer relevant
