### ISSUE TITLE
Public release snagging

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#383]
Issues spotted so far:

- [x] Various dataset issues – https://github.com/mysociety/local-intelligence-hub/issues/364
   - https://github.com/mysociety/local-intelligence-hub/pull/396
- [x] New/old constituency replacement message at top of area page looks bad.
   - https://github.com/mysociety/local-intelligence-hub/pull/384
- [x] Numeric tables on the area page aren’t being converted into bar charts.
   - https://github.com/mysociety/local-intelligence-hub/pull/386
- [x] HOPE not hate MRP dataset cards on area page are missing the bright orange "not to be shared" warning text that used to appear in their card footers.
    - @zarino has confirmed with TCC that they want all members-only data (not just HNH polling) to have a warning like this, so that members know what they can and can’t share publicly.
    - https://github.com/mysociety/local-intelligence-hub/pull/402
- [x] "MP" tab on WMC23 area pages should be renamed "PPCs"
   - https://github.com/mysociety/local-intelligence-hub/pull/385
- [x] We’re missing dataset release/import dates in card footers – didn’t we already complete the work that makes these available? Have we just forgotten to add them to the template?
   - https://github.com/mysociety/local-intelligence-hub/pull/387
- [x] "Favourites" tab on Area page should be hidden for non-logged-in users – @zarino 
   - Part of https://github.com/mysociety/local-intelligence-hub/pull/392
- [x] "Favourite" hearts on Area page (and in Explore page modals – although I think this is already the case) should be hidden for non-logged-in users – @zarino 
   - Part of https://github.com/mysociety/local-intelligence-hub/pull/392
- [x] "TCC member?" advert in Explore page sidebar should _not_ appear for logged-in users
   - Part of https://github.com/mysociety/local-intelligence-hub/pull/392

Bug reports from Bronwen, based on staging site as of 2024-01-17:

- [x] Some datasets ("Support for net zero" and "Estimated households in fuel poverty" at least) have the wrong "Minimum" and "Average" figures when you unfold "About this dataset" on the Explore page. I think it’s counting Northern Irish / Scottish constituencies as "0", when really the "Support for net zero" source data didn’t include NI constituencies, and the "households in fuel poverty" source data didn’t include Scottish or NI constituencies, so they should be excluded from all calculations. Notably, when these datasets are used as a shader, the correct minimum values are shown – @struan 
- [x] When filtering 2025 constituencies by "Estimated households in fuel poverty" (eg: "equal of greater than: 0%"), and then hovering over constituencies on the map, for most constituencies the tooltip contains _two_ percentages separated by a comma (eg: Isle of Wight East or West), whereas others (eg: New Forest East and West, directly above the Isle of Wight) correctly show just a single percentage. What’s going on here? Why are there _two_ percentages in these tooltips, separated by a comma? – @struan
- [x] When filtering 2025 constituencies by any dataset, and hovering over a constituency, the tooltip for many constituencies includes multiple values for "MP name", separated by a comma. I’m surprised it’s able to show _any_ MPs, given these constituencies won’t have MPs until after the next election! There should be no "MP name" when hovering over a 2025 constituency. – @struan 

From @zarino on 2024-01-23:

- [x] 500 error when search term matches a person standing as a PPC in a `WMC23` area with multiple PPCs – https://github.com/mysociety/local-intelligence-hub/issues/410

Would be nice to expunge the last remaining useless dataset descriptions (as they’re now quite prominent in the Explore page dataset picker modal):

- [x] "Churches that have declared a climate emergency" – remove description
- [x] "Constituency age distribution" – remove description
- [x] "Flood risk from rivers or sea" – new description: "Proportion of this constituency at High, Medium, Low, or Very Low risk of flooding."
- [x] "MP Facebook username" – remove description
- [x] "MP Parliament ID" – remove description
- [x] "MP party" – remove description
- [x] "MP signed Possible’s 2019 Onshore Wind Energy open letter" – remove description
- [x] "MP signed The Climate Coalition’s 2019 Net Zero Target joint letter" – remove description
- [x] "MP TheyWorkForYou ID" – remove description
- [x] "MP Twitter username" – remove description
- [x] "MP Wikipedia article" – remove description
- [x] "National Trust properties" and "Number of National Trust properties" – remove descriptions
- [x] "Number of National Trust Members" – remove description
- [x] "Number of onshore windfarms" – remove description
- [x] "Number of Save the Children shops" – remove description
- [x] "Number of Save the Children supporters" – remove description
- [x] "Number of Trussell Trust foodbanks" – remove description
- [x] "Number of Women’s Institute groups" – remove description
- [x] "Number of WWF supporters" – remove description
- [x] "Popular petitions" – remove description
- [x] "Women’s Institute groups" – remove description
- [x] The three CAFOD datasets – remove descriptions
- [x] The two "Christian Aid groups" datasets – remove descriptions
- [x] The two "Number of Great Big Green Week…" datasets – remove descriptions
- [x] The two "RSPB Reserves" datasets – remove description and add `https://opendata-rspb.opendata.arcgis.com/datasets/6076715cb76d4c388fa38b87db7d9d24/explore` as source
- [x] The two "Wildlife Trusts Reserves" datasets – remove descriptions

Datasets not caculating stats (max, min, avg):

- [x] Loss of nature (Hope Not Hate MRP is the actual dataset)

Bugs from morning of 2024-01-24:

- [x] map page - select "current constituencies", then filter by "loss and damage" data set (or many of the others) - sidebar and map disappear, with just the green header left visible

**Comment by struan** [comment]
The datasets not calculating averages etc is because these are datasets with multiple data types underneath them so it's not clear what average you would show.

**Comment by zarino** [comment]
With the merging of https://github.com/mysociety/local-intelligence-hub/pull/425 into `main`, I think we can consider the initial "snagging" completed, and create individual tickets for any further feedback.
