### ISSUE TITLE
consider splitting up JS a bit so we're not loading things we don't need on the front page

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#397]
At the moment all the pages use `all.js` which includes both the chart js and the explore js so we pull in a load of files we don't really need at this point. We might want to split those out at some point.

The counter argument to this is that anyone using the site is presumably going to need those and they are cached for a long time so might as well load them now and the later pages will be fine, especially as, I think, those are non blocking downloads so the page will render anyway.

**Comment by dracos** [comment]
A slightly different point to this is not so much they're being pulled in but that they are not tree-shaken at all, and chart.js is pretty large. Will comment on https://github.com/mysociety/local-intelligence-hub/pull/394

**Comment by struan** [comment]
One suggestion is we should have three files:

* very minimal front page one
* area page
* everything else

Could possibly get a saving by writing the bootstrap code ourselves so we don't need to include this.

**Comment by struan** [comment]
Other potential improvements:

* work out how to get Modal to import and hence tree shake better (assuming we're not writing this ourselves
