### ISSUE TITLE
Confirm public/private status of datasets with TCC

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#399]
- [x] Update all datasets to set privacy field – either public or private
- [x] Will require us to mark datasets as public or private – [TCC have started a spreadsheet to collect this information](https://docs.google.com/spreadsheets/d/10nCxPl6-HPSel6gLQmhLWOfAWr0rImC6gXX2_lYzPjE/edit#gid=0) from partners / partner agreements [update 4/12/23]

**Comment by struan** [comment]
FWIW, all datasets are marked as False by default.

**Comment by emilyk383** [comment]
Public / private dataset permissions on Django checked against TCC dataset spreadsheet indicating permissions, pre-launch (23/1/2024).
TCC as data controller will double check site accuracy on public permissions w/c 30/1/24
TCC will also develop 'master spreadsheet' to ensure permissions, renewal requirements etc are captured in one place - they'll start on this in w/c 30/1/24

**Comment by emilyk383** [comment]
@zarino are you happy this one is done?

**Comment by zarino** [comment]
Yep!
