### ISSUE TITLE
Confirm datasets (core and third-party, at-launch and future)

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#4]
- Which datasets did prototyping week respondents say would be most useful?
- Which datasets did Alex W discover in his mapping excercise?
- Which datasets are we actually able to source ourselves?
- Which datasets will third parties need to provide? And are they happy to do it?
- What location identifiers do the datasets contain? Do they lend themselves to being split/combined by constituency? How would we do that?
- Which of these datasets are “killer datasets” we want to launch with? Which could come later?

Lists of potential datasets:

- Alex W’s dataset audit
- [NPC’s local needs databank](https://www.thinknpc.org/resource-hub/local-needs-databank/) (see "Metadata" section to links to all the source datasets)

**Comment by zarino** [comment]
Core datasets that lots of other stuff hooks on to:

- Constituencies – GSS code, MapIt ID, name, geometry
- MPs – name, TWFY ID, Parliament ID

MP data:

- Party (from WikiData?)
- External profiles / handles (from WikiData?) – Twitter, Facebook, Wikipedia, TWFY
- Date of election
- Majority at last general election
- APPG memberships, ([from Parliament?](https://www.parliament.uk/mps-lords-and-offices/standards-and-financial-interests/parliamentary-commissioner-for-standards/registers-of-interests/register-of-all-party-party-parliamentary-groups/registers-published-in-2022/) – note there’s a new list of members every few months). It’d be great to just get all of an MP’s memberships, but if not, here’s a list of climate/environment/energy/nature-adjacent APPGs, with a ⭐️ next to the handful that Alex W from TCC highlighted:
   - [Air Pollution](https://publications.parliament.uk/pa/cm/cmallparty/221019/air-pollution.htm) ⭐️
   - [Climate Change](https://publications.parliament.uk/pa/cm/cmallparty/221019/climate-change.htm) ⭐️
   - [Community Energy](https://publications.parliament.uk/pa/cm/cmallparty/221019/community-energy.htm)
   - [Cycling and Walking](https://publications.parliament.uk/pa/cm/cmallparty/221019/cycling-and-walking.htm)
   - [Electric Vehicles](https://publications.parliament.uk/pa/cm/cmallparty/221019/electric-vehicles.htm)
   - [Energy Costs](https://publications.parliament.uk/pa/cm/cmallparty/221019/energy-costs.htm)
   - [Energy Security](https://publications.parliament.uk/pa/cm/cmallparty/221019/energy-security.htm)
   - [Environment](https://publications.parliament.uk/pa/cm/cmallparty/221019/environment.htm) ⭐️
   - [Farming](https://publications.parliament.uk/pa/cm/cmallparty/221019/farming.htm)
   - [Fisheries](https://publications.parliament.uk/pa/cm/cmallparty/221019/fisheries.htm)
   - [Forestry and Tree Planting](https://publications.parliament.uk/pa/cm/cmallparty/221019/forestry-and-tree-planting.htm)
   - [Fuel Poverty and Energy Efficiency](https://publications.parliament.uk/pa/cm/cmallparty/221019/fuel-poverty-and-energy-efficiency.htm)
   - [Green New Deal](https://publications.parliament.uk/pa/cm/cmallparty/221019/green-new-deal.htm)
   - [Health and the Natural Environment](https://publications.parliament.uk/pa/cm/cmallparty/221019/health-and-the-natural-environment.htm)
   - [Marine Energy](https://publications.parliament.uk/pa/cm/cmallparty/221019/marine-energy.htm)
   - [Microplastics](https://publications.parliament.uk/pa/cm/cmallparty/221019/microplastics.htm)
   - [Nature](https://publications.parliament.uk/pa/cm/cmallparty/221019/nature.htm) ⭐️
   - [Net Zero](https://publications.parliament.uk/pa/cm/cmallparty/221019/net-zero.htm)
   - [Parks and Green Spaces](https://publications.parliament.uk/pa/cm/cmallparty/221019/parks-and-green-spaces.htm)
   - [Renewable and Sustainable Energy](https://publications.parliament.uk/pa/cm/cmallparty/221019/renewable-and-sustainable-energy.htm)
   - [Sustainable Flood and Drought Management](https://publications.parliament.uk/pa/cm/cmallparty/221019/sustainable-flood-and-drought-management.htm)
   - [Tidy Britain](https://publications.parliament.uk/pa/cm/cmallparty/221019/tidy-britain.htm)
   - [Waterways](https://publications.parliament.uk/pa/cm/cmallparty/221019/waterways.htm)
   - [Wetlands](https://publications.parliament.uk/pa/cm/cmallparty/221019/wetlands.htm)
   - [Woods and trees](https://publications.parliament.uk/pa/cm/cmallparty/221019/woods-and-trees.htm)
- Non-parliamentary group memberships:
   - Conservative Environment Network:
      - [Their "caucus"](https://www.cen.uk.com/our-caucus)
      - [Their "Net Zero Champions"](https://www.cen.uk.com/climate)
      - [Their "Nature Champions"](https://www.cen.uk.com/nature)
   - SERA (Labour):
      - [Their "Executive Committee"](https://www.sera.org.uk/executive_committee) – seems to only include a couple of MPs?

Constituency data:

- TCC MRP opinion polling data
- % of households in fuel poverty (from…??)
- % of households at risk of flooding (from…??)
- % of children living in poverty ([from House of Commons Library](https://commonslibrary.parliament.uk/constituency-data-child-poverty/))
- IMD (deprivation) in this constituency – [England](https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019), [Wales](https://gov.wales/welsh-index-multiple-deprivation), [Scotland](https://www.gov.scot/collections/scottish-index-of-multiple-deprivation-2020/), and [Northern Ireland](https://www.nisra.gov.uk/statistics/deprivation/northern-ireland-multiple-deprivation-measure-2017-nimdm2017)
- Median household energy efficiency in this constituency – [England and Wales](https://www.ons.gov.uk/peoplepopulationandcommunity/housing/articles/energyefficiencyofhousinginenglandandwales/2022)
- Land use / rural-urban measure in this constituency ([House of Commons Library](https://commonslibrary.parliament.uk/constituency-dashboard/) seems to get this from [CLC](https://land.copernicus.eu/pan-european/corine-land-cover/clc2018?tab=mapview), there’s also the [RUC](https://geoportal.statistics.gov.uk/datasets/1858f82f2e6d4f28bbf1952fd5973bff/about) but it only covers England – should ask Alex P for a UK-wide data source)
- Access to public green space in this constituency ([from ONS](https://www.ons.gov.uk/economy/environmentalaccounts/datasets/accesstogardensandpublicgreenspaceingreatbritain))
- Year on year change in number of businesses in this constituency ([from House of Commons Library](https://commonslibrary.parliament.uk/research-briefings/sn06152/))
- Constituency is within an area that has received "levelling up" funds (2021 list available [from GOV.UK](https://www.gov.uk/government/publications/levelling-up-fund-first-round-successful-bidders), 2022 list hasn’t been announced yet)
- 2016 Brexit vote split in this constituency
- % of eligible voters who turned out at the most recent general election in this constituency

Movement data:

- FoE supporters by constituency
- National Trust supporters by constituency
- Oxfam shops near this constituency
- National Trust properties near this constituency
- Parish groups and churches near this constituency (CAFOD)
- Community energy projects near this constituency ([from Community Energy England](https://communityenergyengland.org/pages/nationalmap))

**Comment by ajparsons** [comment]
For deprivation, can also create constituency level versions of the composite ranking fairly easily (I've already done the LA level, the maths is simple) https://mysociety.github.io/composite_uk_imd/

**Comment by ajparsons** [comment]
Alignment between local government control and local MP

**Comment by zarino** [comment]
Notes from team call about this:

- There are definitely APPGs / select committees that are of core interest and might be good to make more accessible, but it’s possible that campaigners might be interested in an MP’s membership of _any_ select committee, often quite tangential to climate stuff, depending on the campaign.
- Writing a scraper for APPG memberships wouldn’t be too hard – they all share the same format. We have code in ParlParse for matching MP names from strings.
- We can re-export our deprivation and rurality data into constituency buckets – will take @ajparsons a few weeks.

Top choices:

- Age buckets from House of Commons Library (so that we can get an example of a "complex" dataset with multiple buckets per constituency)
- Fuel poverty (as a very topical example of a social issue) – @sequencefree has offered to help source data
- Access to green space (as an example of environmental data)
- Loop back to APPGs and Select Committees after that, for more MP data

**Comment by zarino** [comment]
I’ve created a milestone to track these data import tasks: https://github.com/mysociety/local-intelligence-hub/milestone/5
