### ISSUE TITLE
Review list of APPGs

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#431]
Check that we're

* not missing any important environment ones (e.g. Wetlands?)
* and not including ones which are not environmental.

**Comment by emilyk383** [comment]
@struan is this one we should assign to @juliacush?

**Comment by juliacush** [comment]
I've just emailed Holly to see if GA have a list of all climate & nature APPGs, but added that if not I'll happily make one.

**Comment by juliacush** [comment]
Will know size of project after first register is published after 31st March, but initial notes here: https://docs.google.com/document/d/1N8eewxLeeqYNFBAxW1gAvPerdlfb6o_H3xPI4KeyuEI/edit?usp=sharing

**Comment by zarino** [comment]
Two options:

1. We could update to latest climate-related APPGs, but we’ll still only have officers, and there’ll be fewer officers now (4 rather than unlimited)
2. We could wait 6 weeks for full APPG memberships
