### ISSUE TITLE
Add disability census data to LIH

### ISSUE THREAD

**Issue by juliacush** [mysociety/local-intelligence-hub#437]
Request from Gaibhain from United Response: "Is it possible to integrate disability figures gathered from the last census as well? If we were able to identify approx. how many disabled people lived in each constituency, that would be a powerful statistic for us to present to elected representatives."

I assume this: https://commonslibrary.parliament.uk/constituency-data-disability-2021-census/#single_constituency

**Comment by zarino** [comment]
Closing in favour of #572, which links back here.
