### ISSUE TITLE
redirect original demo page to live site

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#438]
The [github pages demo](https://pages.mysociety.org/local-intelligence-hub/) site come quite high in search results meaning people accidentally find it. We should remove it and redirect people to the live site.

**Comment by zarino** [comment]
In the meantime, we could add a Disallow rule to https://github.com/mysociety/mysociety.github.io/blob/master/robots.txt with:

```
User-agent: *
Disallow: /local-intelligence-hub/
```

…To show Google that we don’t want that page to appear in results?

**Comment by struan** [comment]
I've updated the pages thing with a custom domain so it redirects to the main site.

**Comment by zarino** [comment]
Whoa, that was easy!
