### ISSUE TITLE
Make a plan for how to handle pre and post election data

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#453]
Things to consider:

* what are we going to do about MP data (pre election I assume nothing)
* do we remove MP contact details? What do we say on area pages given MPs are technically not MPs
* do we want to link to DC in any capacity?
* setting expectations about how soon things will be up to date post election esp wrt to parliament data etc

**Comment by struan** [comment]
Might need to either hide or clear second place party and election results data in the short term post election as not sure how quick parliament will be in updating this.

**Comment by zarino** [comment]
This has mostly been replaced by #566 and #568.

Re: "setting expectations" on updated data, completing #571 would get us some way towards that. For data about the new MPs, we’ll just have to wait. I think people will understand that new MPs won’t have voted on many issues yet, or joined many committees/APPGs.
