### ISSUE TITLE
Re-ordering of LIH bar charts so they go from low to high 

### ISSUE THREAD

**Issue by juliacush** [mysociety/local-intelligence-hub#465]
Request from Jonathan F on democracy club slack 
<img width="353" alt="Screenshot 2024-02-15 at 13 37 42" src="https://github.com/mysociety/local-intelligence-hub/assets/135219396/85d9ab46-794b-4d4e-9314-c3a884a940d3">
e.g.
<img width="439" alt="Screenshot 2024-02-15 at 13 33 38" src="https://github.com/mysociety/local-intelligence-hub/assets/135219396/255beffd-b7f0-4cdc-a62a-d077781084e9">

**Comment by lucascumsille** [comment]
I tried figuring out how the ordering was being done, chart.js takes the order on the hidden rows on the tables to create the dataset for graphs, so this seems to be a server-side issue. As a note the ordering on the explore page when sorting dataset is correct so is something happening in the area pages.

**Comment by zarino** [comment]
I’ve fixed this for the three most prominent MRP datasets now, by setting a custom `order` attribute on their `DataType`s in the django admin.

I guess, ideally, in future, we should update the import scripts to set this order automatically.
