### ISSUE TITLE
Can we tell LIH users which of the new constituencies will be their new constituency?

### ISSUE THREAD

**Issue by juliacush** [mysociety/local-intelligence-hub#466]
E.g. indicate that my new constituency would be Leeds Central and Headingley.
<img width="790" alt="Screenshot 2024-02-15 at 13 42 45" src="https://github.com/mysociety/local-intelligence-hub/assets/135219396/7eff8b1b-8dc3-4e85-a98f-87e0d601d8f8">

**Comment by zarino** [comment]
This feels less necessary now, partly because our postcode search results page now tells you which 2025 constituency you’re in, and partly because we expect very few people will be visiting the old constituency pages from now on. Going to close.
