### ISSUE TITLE
Flickering charts / graphs on area page

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#476]
I‘ve spotted this myself, and it was also reported by a user last week:

> A good collection of information.  I haven't been through it all but it's really useful to see. I'm a bit confused by the disappearing graphs, they don't stay long enough to understand them!

The charts sometimes seem to flicker and then disappear. Not sure what causes it. Some incompatibility with chart.js’s responsive mode and the CSS grid layout?

**Comment by zarino** [comment]
One approach to this could be to drop chart.js and build charts in pure CSS: https://9elements.com/blog/responsive-bar-charts-in-html-and-css/

**Comment by lucascumsille** [comment]
@zarino I haven't being able to replicate this issue, so far I have tried:

- Chrome
- Firefox
- Safari
- Microsoft edge

I tried resizing the screen, hide/show on the inspector, but I don't see any odd behaviour. The only thing that is kind of odd is that on Edge you need to click a bar to know its percentage, while in the other ones you just need to hover, so on Edge you probably wouldn't know about the percentages.

Happy to drop the chart.js and just do CSS. Let me know.

**Comment by zarino** [comment]
Hmmmm, weird. I’m wary of spending time replacing the current charts, if we can’t reliably reproduce the problem. Although if #569 and #465 turn out to be hard/impossible to do in chart.js, we can reconsider.
