### ISSUE TITLE
Unable to filter by party

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#484]
Filtering by `party__in` or `party__not_in` on the Explore page doesn’t work:

<img width="1522" alt="Screenshot 2024-02-23 at 16 54 57" src="https://github.com/mysociety/local-intelligence-hub/assets/739624/958c491a-54b0-4bc9-a6e1-3f5c0fc83293">

Could this be a regression caused by the MP metadata changes in #467 ?

**Comment by struan** [comment]
Fixed by #481
