### ISSUE TITLE
Enable display, search, and filtering of local authorities on the Hub

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#487]
- [x] - Local authorities as an area type
- [x] - Page for a local authority – won’t have an MP!
- [x] - Handling for overlapping local authority boundaries – treat Counties as a separate "layer" on the Explore map?
- [x] - Make search work

**Comment by zarino** [comment]
Interesting to see how https://www.lcat.uk (launched yesterday?) handles mapping of "local authorities". It lets you choose between "UK Counties" and "Local Authority Districts":

<img width="887" alt="Screenshot 2024-02-29 at 08 51 21" src="https://github.com/mysociety/local-intelligence-hub/assets/739624/99b0f2b2-d8b8-4097-98dc-a91e61ec7c7d"><br>

It’s hard to tell what’s going on, but I think their two options _largely_ map to the following MapIt area types:

| Area type | “UK Counties“ | “Local Authority Districts” |
| --- | --- | --- |
| [County council](https://mapit.mysociety.org/areas/CTY.html) | ✅ |  |
| [District council](https://mapit.mysociety.org/areas/DIS.html) |  | ✅ |
| [London Borough council](https://mapit.mysociety.org/areas/LBO.html) | ✅ | ✅ |
| [Northern Irish council](https://mapit.mysociety.org/areas/LGD.html) |  | ✅ |
| [Metropolitan District council](https://mapit.mysociety.org/areas/MTD.html) |  | ✅ |
| [Unitary Authority](https://mapit.mysociety.org/areas/UTA.html) | ✅ | ✅ |

Although they’re doing something odd with some of the boundaries, eg:

- “UK Counties” combines Isles Of Scilly into Cornwall (Unitary) Council.
- “UK Counties” splits the Bournemouth Christchurch and Poole (Unitary) Council (from “Local Authority Districts”) into two separate "Bournemouth" and "Poole" areas, with Christchurch subsumed into Dorset.
- “UK Counties” splits the Northern Irish councils (from “Local Authority Districts”) into smaller parts I don’t recognise, like “Mid and East Antrim” being split into “Balymena” and “Larne”.
- “UK Counties” includes a “Merseyside” area, which appears to cover Liverpool City, Sefton Borough, Knowsley Borough, and St Helens Borough – but _isn’t_ the LCR Combined Authority because it cedes Halton over into “Cheshire” and, bizarrely, splits out Wirral into a separate, incorrectly named area, “Halton”!!

**Comment by struan** [comment]
Looking at this I think it's possibly useful for their use case which is mostly about expressing things about the area you live but I am not sure will make sense for us as we need our data to be connected to recognisable entities you can interact with. I think that Unitary, County, Scottish, Welsh and NI Councils as one level and District Councils (England only) probably makes sense as a set of divisions for us and we just accept that the latter does not cover the whole country.

Interesting to note that their UK Counties boundaries are much simplified compared to Local Authority Districts:

UK Counties:
<img width="779" alt="Screenshot 2024-02-29 at 09 59 11" src="https://github.com/mysociety/local-intelligence-hub/assets/5310/0cfea3ee-f630-4d83-9560-984c0a0f9399">

Local Authority Districts:
<img width="803" alt="Screenshot 2024-02-29 at 09 59 28" src="https://github.com/mysociety/local-intelligence-hub/assets/5310/d4c50e96-a146-4a1f-b5be-c97611657b05">

**Comment by struan** [comment]
Launched!
