### ISSUE TITLE
Investigate missing (?) Wildlife Trust reserves

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#494]
Tom from Save The Children noted that when you list the constituencies with Wildlife Trusts reserves, there are seemingly only 88 constituencies with a reserve:

https://www.localintelligencehub.com/explore/?view=table&columns=wildlife_trusts_reserves_count

88 constituencies seems quite low, given RWST list [2213 reserves on their website](https://www.wildlifetrusts.org/nature-reserves).

He wondered whether we were somehow truncating results, given the list of constituency names stops at the letter N (Makerfield, Neath, Newbury…) and, indeed, picking a constituency near the end of the alphabet, we do seem to be missing the five reserves in [Ynys Môn](https://mapit.mysociety.org/area/66115.html) – [Cemlyn](https://www.northwaleswildlifetrust.org.uk/node/376), [Porth Diana](https://www.northwaleswildlifetrust.org.uk/node/381), [Cors Goch](https://www.northwaleswildlifetrust.org.uk/node/394), [Mariandyrys](https://www.northwaleswildlifetrust.org.uk/node/382), and [Caeau Pen y Clip](https://www.northwaleswildlifetrust.org.uk/node/402).

But, the "N" cut-off is a red herring. It looks like we’re missing reserves across the country. eg: [Hartington Meadows](https://www.derbyshirewildlifetrust.org.uk/nature-reserves/hartington-meadows) in the [Derbyshire Dales](https://mapit.mysociety.org/area/65799.html) constituency, [Harvest Hill](https://www.warwickshirewildlifetrust.org.uk/HarvestHill) in [Coventry North West](https://mapit.mysociety.org/area/65575.html), and [Romney Marsh](https://www.kentwildlifetrust.org.uk/nature-reserves/romney-marsh-visitor-centre-and-nature-reserve) in [Folkestone and Hythe](https://mapit.mysociety.org/area/65779.html).

[Our import script for Wildlife Trust reserves](https://github.com/mysociety/local-intelligence-hub/blob/bd035cbc070b13dd86417bd6ecab1ffce09d5f98/hub/management/commands/generate_wildlife_trust_nature_reserves_csv.py) calls the Wildlife Trusts API in a loop, and results in a CSV with about 1569 reserves in it.

Is there a chance that the Wildlife Trusts API is just missing a bunch of reserves?

**Comment by zarino** [comment]
This bug appears to be back. We currently appear to have only 45 Wildlife Trusts reserves, across 15 constituencies!?:

https://www.localintelligencehub.com/explore/?view=table&columns=wildlife_trusts_reserves_count

<img width="818" alt="Screenshot 2024-04-26 at 13 04 55" src="https://github.com/mysociety/local-intelligence-hub/assets/739624/59f0c497-bca8-4be8-98f6-69aca77d6d63">

**Comment by struan** [comment]
looks like I used a bad import file. I've regenerated the data now and there's hundreds now.
