### ISSUE TITLE
Import updated (2024/25) Aid Alliance Power Postcodes groups

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#499]
Aid Alliance operates a project called “Power Postcodes”, training and supporting resident groups in key constituencies around the UK. We currently display some Power Postcodes data in the Hub (#101) but some of Aid Alliance’s Power Postcode groups have changed recently, so it’d be good to update.

I’ve asked Sophie from Aid Alliance to provide us with a spreadsheet of their (~70) currently active groups, with columns for the group’s name, Facebook URL, current constituency, and future constituency. It sounds like they might be happy for this to be public data on the Hub, but we need to confirm.

Sophie’s also going to look at getting us the rough "priority" of each group – all groups are important, but some are particularly in need of extra support, or particularly open to collaboration with other organisations, and I suggested it might be useful to expose this "priority" list to signed-in TCC members, so they can spot when they’ll be doing work in a constituency that Aid Alliance is particularly keen on growing.

**Comment by struan** [comment]
Fixed in https://github.com/mysociety/local-intelligence-hub/commit/1b23084dba2f77c1dce9aa2a4ef0d7049f90cf7b
