### ISSUE TITLE
Write initial version of tech spec for MVP

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#5]
Based on content of prototype.

Assume datasets will be manually added by us/TCC as CSVs. No scraping or APIs.

- How will datasets be associated with constituencies?
- How will accounts / dataset privacy be managed?
- Any other feedback from prototyping report that we should incorporate?

**Comment by zarino** [comment]
@struan Has made a start on a tech spec.

**Comment by struan** [comment]
In progress Tech spec is here: 

https://docs.google.com/document/d/1VgvSEcNBbmlo6BEJfWzERvz0x3dAFKQgm8kKN7iFpAc/edit#heading=h.pdd0pq1vsm2c

**Comment by JenMysoc** [comment]
Version one is finished - more will be added as time goes on but considering this done for the moment?

**Comment by struan** [comment]
We've got a chat about this tomorrow morning so lets see what comes out of that and then maybe we mark this as done. I'll update the title to say initial version :)
