### ISSUE TITLE
Import data on Local Authority Climate Action Scorecards

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#514]
At the very least, it’d be good to have:

- a dataset for the council’s _total_ score as a % figure – which we can display as a big number on the council page
- a dataset for the council’s section scores (with a datatype per section) as % figures – which we can display as a table on the council page

We need to be careful that we _don’t_ display comparisons with a "national average" though. If possible, it’d be good to compare with the average of councils of the same type, but I’m not sure how we’d do this, given the way we currently handle metadata (min, max, average) on datasets.

**Comment by struan** [comment]
Fixed in #531
