### ISSUE TITLE
Two instances of 'consider climate change a high priority' showing different figures on councils LIH

### ISSUE THREAD

**Issue by juliacush** [mysociety/local-intelligence-hub#533]
e.g. for leeds city council 

Consider climate change a high priority

54%

52.9% national average

-
Consider Climate Change a High Priority

54%

50.2% national average

![Image](https://github.com/mysociety/local-intelligence-hub/assets/135219396/f93bd86d-ba66-4b68-958f-f5c4f20cd297)

**Comment by zarino** [comment]
This is no longer the case. I assume something we’ve done in the meantime has fixed it.

![Screenshot 2024-07-03 at 12-33-59 Leeds City Council](https://github.com/mysociety/local-intelligence-hub/assets/739624/78a30bc2-fdce-4793-9066-00b381df4bd8)
