### ISSUE TITLE
Update area pages for post general election

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#566]
Once the election is over we'll need to make some updates to the site and scripts:

 - [x] update MP import scripts to populate WMC23 pages
 - [x] update new are page to show MP and not PPCs (do we just remove PPCs entirely?)
 - [x] add warning to WMC area pages that they are now no longer relevant
 - [x] disable/delete PPC update script as it shouldn't be run again
 - [ ] check that MP details (majority etc) import scripts are pointing at the right place.
 - [x] remove WMC areas from the postcode lookup

**Comment by zarino** [comment]
Probably also want to update the "new constituencies" descriptions on the `/location/search` disambiguation page and `/explore` page area type modal. Not sure what _to_, mind…

**Comment by struan** [comment]
Need to find a replacement for https://commonslibrary.parliament.uk/research-briefings/cbp-8749/ for the 2024 general election.
