### ISSUE TITLE
Can bar charts include % per row?

### ISSUE THREAD

**Issue by juliacush** [mysociety/local-intelligence-hub#569]
Makes it easier for people to use statistics in written communication

**Comment by zarino** [comment]
The bar charts _do_ show percentages on hover – but I agree, showing stuff on hover is a nasty hack that doesn’t work on touchscreens, or in screenshots, so maybe it’s best to _always_ display the percentage for each row.

<img width="347" alt="Screenshot 2024-07-03 at 11 02 23" src="https://github.com/mysociety/local-intelligence-hub/assets/739624/91635803-332a-41bf-8c6d-256f302cca42">

**Comment by lucascumsille** [comment]
Apparently this is possible with `chart.js` using [datalabels plugin](https://chartjs-plugin-datalabels.netlify.app/guide/getting-started.html#installation) I'll give it a try once I can set up my local.

**Comment by zarino** [comment]
@lucascumsille The thing to keep an eye out for will be how tiny the text has to be, to fit inside those bars. Maybe we might need to make the bars "thicker"… :-/
