### ISSUE TITLE
Long term thinking around boundary changes

### ISSUE THREAD

**Issue by ajparsons** [mysociety/local-intelligence-hub#57]
We're producing a lot of data around constituencies, but that's likely to change in the boundary review coming into effect before the next election. 

The boundaries should be finalised a while in advance of the election - but this affects different kinds of data in different ways. 

Initial thoughts:

## Constituency-level (derived from lower geographies) 

Given boundary files we can produce updates through new mappings of LSOA to constituency. Our IMD data for instance we could create a new dataset well in advance.

##  Constituency-level (third party)

Can create a best fit mapping where possible (few constituencies are completely unrecognisable) - and probably have good enough data for most constituencies based on existing data.

## MP level data

Out of date in the election anyway - many may move constituency - but if tagged to a unique identifier should be fine.

As adding datasets we should keep track (edit this ticket?) of which datasets are in which category.

**Comment by zarino** [comment]
Snippet from an email I sent to TCC this morning:

> I think our eventual decision on a route forward will be based on what TCC members expect – how quickly they’ll want to switch into using the new boundaries, and how they would expect to map their existing constituency/MP data into the new boundaries/MPs. We can explore this further during the testing early next year.

**Comment by ajparsons** [comment]
Write up here: https://docs.google.com/document/d/144CO0QeVzVbNLFtCafB2rNl54AqHJZtfI3oAL0oFMpk/edit#

Will wait a few days, and then can circulate for opinions with FoE.

**Comment by ajparsons** [comment]
@zarino : assuming this is all ok enough I should share with FoE?

**Comment by zarino** [comment]
@ajparsons Yes, share away. I notice Chiara sent over some lookup tables on 21st March – don’t know whether affects the document at all?

**Comment by ajparsons** [comment]
Have shared! I think the next step on this would be to create tickets from the steps, if the direction is broadly right.

**Comment by zarino** [comment]
@ajparsons has broken this down into tasks, and put them into a milestone here: https://github.com/mysociety/local-intelligence-hub/milestone/8
