### ISSUE TITLE
post election fixes

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#579]
- [x] Fix election results import so a person can have a result in an old and new constituency
- [x] Make sure persondata imports don't delete old constituency data when importing new constituency data
- [x] Update persondata imports areas available settings
- [ ] Fix duplicate MP detection
- [ ] Update election results script to point at correct HoC library source for 2024 GE once available
- [x] More permanent solution for getting correct person type than hardcode MP in the code

**Comment by struan** [comment]
Looks like it will be the 12th of July before HoC library publishes the full election results for 2024 according to [this page](https://commonslibrary.parliament.uk/research-briefings/cbp-10009/?_gl=1*q11n29*_up*MQ..*_ga*MTA5MjYxNDA2MC4xNzIwNDI5NjI3*_ga_14RSNY7L8B*MTcyMDQyOTYyNy4xLjAuMTcyMDQyOTYzMi4wLjAuMA..).

**Comment by struan** [comment]
Need to sort out which person datasets are specific to an area type and which are not, and then set the area_type accordingly and use that in the explore and are pages.

**Comment by zarino** [comment]
HoC Library has now published [detailed election results by constituency](https://commonslibrary.parliament.uk/research-briefings/cbp-10009/) so you can import those, @struan 🎉
