### ISSUE TITLE
Update FoE State of the Environment report URLs

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#599]
We already display an early version of FoE’s “State of the Environment” reports, as PDFs, on the Hub:

<img width="454" alt="Screenshot 2024-08-01 at 11 59 56" src="https://github.com/user-attachments/assets/92237a2a-77b3-434e-80e5-acd24c374e05">

The information from those PDF reports has now been worked into their "Near You" webpages – accessible by postcode search at https://groups.friendsoftheearth.uk/near-you/constituency

Can we guess the slugs for their Near You pages (eg: `/near-you/constituency/north-herefordshire`) or will we need to ask FoE for a full list?

Also, now the information is all public (and no longer in PDFs) FoE say they’re happy for the dataset to be public access on the Hub, rather than members-only. And we’ll want to update the description of the dataset too, since they’re no longer "still under active development".

**Comment by struan** [comment]
It turns out the urls are pretty guessable, with a few exceptions.
