### ISSUE TITLE
Investigate feasibility of importing Written Questions and Early Day Motions on climate/nature topics (from TheyWorkForYou?)

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#603]
Data on MPs voting on climate/nature bills is going to be thin on the ground for a while, and with so many new MPs this intake, we can’t rely on data from the previous parliament to give us a full picture either. So we need to looks for other indicators of MP support for / opposition of climate and nature issues, from their other activities in parliament.

Written Questions and Early Day Motions could be two such sources of data.

- Where do we get the data from?
- How do we filter down to just climate and nature related WQs/EDMs?
- How do we present it to be most useful?

**Comment by zarino** [comment]
> Where do we get the data from?

Two options for Written Questions/Answers:

- [TheyWorkForYou](https://www.theyworkforyou.com/api/docs/getWrans)’s `/api/docs/getWrans` API endpoint
- [UK Parliament](https://questions-statements-api.parliament.uk/index.html)’s `/api/writtenquestions/questions` API endpoint

> How do we filter down to just climate and nature related WQ’s

My instinct would be to use API search params to return a combination of:

- all questions submitted to DESNZ, DEFRA, and maybe DfT?
- any questions submitted to other departments, which contain terms like `net zero`, `climate change`, `climate emergency`, `climate crisis`, `nature`, `biodiversity`, `pollution`, `decarbonisation`, `carbon capture`, `renewable energy`, `onshore wind`, `offshore wind`, `wind turbine`, `solar panel`, `solar farm`, etc

The former will catch most climate/nature related questions, while the latter will mop up any remainder submitted to the other departments, and hopefully, if we can make the search terms specific enough, we won’t get too many false-positives.

> How do we present it to be most useful?

Perhaps show the titles of the 3 most recent questions submitted by the constituency’s MP (each one linking to the full question on TheyWorkForYou or the UK Parliament site), and then a button that unfolds a full list in place?

**Comment by ajparsons** [comment]
Related  https://github.com/mysociety/twfy-votes-django/issues/2

**Comment by struan** [comment]
I think both of these are now done, at least in an initial form. Will probably need some improvements along the way.

The wrans this has a cron so should run every day and fetch the previous days wrans from TWFY. I might add a once a week to do the last seven days on a Sunday just as a backup.
