### ISSUE TITLE
Reinstate MP majority dataset for Summer 2024 intake of MPs

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#605]
Should be a very quick fix!

Somehow, when we added the 2024 election results, we didn’t _also_ separate out the winning MP’s majority into its own dataset, meaning it’s missing from MPs’ pages now, and shows as "old constituencies" only on the data sources page.

**Comment by zarino** [comment]
We need this in place before the demo to MP Watch on Wednesday 18th September.

**Comment by struan** [comment]
Done
